// <auto-generated />
using System;
using Hotel_Reservation_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel_Reservation_System.Migrations
{
    [DbContext(typeof(MyAppDbContext))]
    partial class MyAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingService", b =>
                {
                    b.Property<int>("BookingsId")
                        .HasColumnType("int");

                    b.Property<int>("ServicesId")
                        .HasColumnType("int");

                    b.HasKey("BookingsId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("BookingServices", (string)null);
                });

            modelBuilder.Entity("Hotel_Reservation_System.Data.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Hotel_Reservation_System.Data.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "1@gmail.com",
                            Name = "Nour El den",
                            Phone = "010"
                        },
                        new
                        {
                            Id = 2,
                            Email = "2@gmail.com",
                            Name = "Anas",
                            Phone = "010"
                        },
                        new
                        {
                            Id = 3,
                            Email = "3@gmail.com",
                            Name = "Seif",
                            Phone = "010"
                        },
                        new
                        {
                            Id = 4,
                            Email = "4@gmail.com",
                            Name = "Ahmed",
                            Phone = "010"
                        },
                        new
                        {
                            Id = 5,
                            Email = "5@gmail.com",
                            Name = "Omar",
                            Phone = "010"
                        });
                });

            modelBuilder.Entity("Hotel_Reservation_System.Data.Models.GuestProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId")
                        .IsUnique();

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.ToTable("GuestProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Giza",
                            DateOfBirth = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            LoyaltyPoints = 1000,
                            NationalId = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza",
                            DateOfBirth = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 2,
                            LoyaltyPoints = 800,
                            NationalId = "123789456"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Cairo",
                            DateOfBirth = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 3,
                            LoyaltyPoints = 1500,
                            NationalId = "456789123"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Cairo",
                            DateOfBirth = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 4,
                            LoyaltyPoints = 500,
                            NationalId = "321456987"
                        });
                });

            modelBuilder.Entity("Hotel_Reservation_System.Data.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Des 1",
                            Location = "Cairo",
                            Name = "Hotel 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Des 2",
                            Location = "Giza",
                            Name = "Hotel 2"
                        });
                });

            modelBuilder.Entity("Hotel_Reservation_System.Data.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("HotelId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Comment 1",
                            Date = new DateTime(2025, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            HotelId = 1,
                            Rating = 4
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Comment 2",
                            Date = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            HotelId = 1,
                            Rating = 3
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Comment 3",
                            Date = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            HotelId = 1,
                            Rating = 4
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Comment 4",
                            Date = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            HotelId = 2,
                            Rating = 4
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Comment 5",
                            Date = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            HotelId = 2,
                            Rating = 3
                        });
                });

            modelBuilder.Entity("Hotel_Reservation_System.Data.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 10,
                            HotelId = 1,
                            IsAvailable = true,
                            PricePerNight = 120m,
                            RoomNumber = "R1"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 10,
                            HotelId = 1,
                            IsAvailable = true,
                            PricePerNight = 80m,
                            RoomNumber = "R2"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 10,
                            HotelId = 1,
                            IsAvailable = true,
                            PricePerNight = 100m,
                            RoomNumber = "R3"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 8,
                            HotelId = 2,
                            IsAvailable = true,
                            PricePerNight = 50m,
                            RoomNumber = "R4"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 5,
                            HotelId = 2,
                            IsAvailable = true,
                            PricePerNight = 15m,
                            RoomNumber = "R5"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 15,
                            HotelId = 2,
                            IsAvailable = true,
                            PricePerNight = 110m,
                            RoomNumber = "R6"
                        });
                });

            modelBuilder.Entity("Hotel_Reservation_System.Data.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Des",
                            Name = "Spa",
                            Price = 40m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Des",
                            Name = "House Keeping",
                            Price = 5m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Des",
                            Name = "Gym",
                            Price = 30m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Des",
                            Name = "Swimming Pool",
                            Price = 50m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Des",
                            Name = "Message",
                            Price = 60m
                        });
                });

            modelBuilder.Entity("BookingService", b =>
                {
                    b.HasOne("Hotel_Reservation_System.Data.Models.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_Reservation_System.Data.Models.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hotel_Reservation_System.Data.Models.Booking", b =>
                {
                    b.HasOne("Hotel_Reservation_System.Data.Models.Guest", "Guest")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_Reservation_System.Data.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Hotel_Reservation_System.Data.Models.GuestProfile", b =>
                {
                    b.HasOne("Hotel_Reservation_System.Data.Models.Guest", "Guest")
                        .WithOne("Profile")
                        .HasForeignKey("Hotel_Reservation_System.Data.Models.GuestProfile", "GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Hotel_Reservation_System.Data.Models.Review", b =>
                {
                    b.HasOne("Hotel_Reservation_System.Data.Models.Guest", "Guest")
                        .WithMany("Reviews")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_Reservation_System.Data.Models.Hotel", "Hotel")
                        .WithMany("Reviews")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Hotel_Reservation_System.Data.Models.Room", b =>
                {
                    b.HasOne("Hotel_Reservation_System.Data.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Hotel_Reservation_System.Data.Models.Guest", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Hotel_Reservation_System.Data.Models.Hotel", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Hotel_Reservation_System.Data.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
